apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: full-stack-fastapi-base

commonLabels:
  app: full-stack-fastapi

resources:
  - secret.yaml
  - configmap.yaml
  - postgresql.yaml
  - backend.yaml
  - frontend.yaml
  - route.yaml

images:
  - name: backend-image
    newName: quay.io/cfchase/full-stack-fastapi-backend
    newTag: latest
  - name: frontend-image
    newName: quay.io/cfchase/full-stack-fastapi-frontend
    newTag: latest