apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: full-stack-fastapi-staging

namespace: full-stack-fastapi-staging

resources:
- ../../base

patchesStrategicMerge:
- environment-patch.yaml

images:
- name: backend-image
  newTag: staging
- name: frontend-image
  newTag: staging

configMapGenerator:
- behavior: merge
  literals:
  - environment=staging
  name: full-stack-fastapi-config

secretGenerator:
- behavior: merge
  literals:
  - postgres-user=postgres
  - postgres-password=staging-password
  - first-superuser-password=staging-password
  - secret-key=staging-secret-key-change-in-production
  name: full-stack-fastapi-secrets
