apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    spec:
      initContainers:
      - name: prestart
        env:
        - name: ENVIRONMENT
          value: "production"
      containers:
      - name: backend
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: BACKEND_CORS_ORIGINS
          value: '["https://full-stack-fastapi.apps.cluster.local"]'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2