apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: full-stack-fastapi-production

namespace: full-stack-fastapi

resources:
- ../../base

patchesStrategicMerge:
- environment-patch.yaml
- resource-limits.yaml

images:
- name: backend-image
  newTag: latest
- name: frontend-image
  newTag: latest

configMapGenerator:
- behavior: merge
  literals:
  - environment=production
  name: full-stack-fastapi-config

secretGenerator:
- behavior: replace
  envs:
  - production-secrets.env
  name: full-stack-fastapi-secrets
